### ISSUE TITLE
Digital number control does not display the digits

### ISSUE THREAD

**Issue by dl1ksv** [ghostop14/gr-guiextra#2]
Setting the thousands separator to period makes the digits disappear.
Switching back to comma or none makes them appear again.

**Comment by ghostop14** [comment]
Thx, I'll check it out tonight and push an update

**Comment by ghostop14** [comment]
Fixed and pushed an update.  Apparently python's format() function doesn't like periods as the separator.  Used an intermediate symbol to get the period to work but it should be good now.
