### ISSUE TITLE
Digital number control output message port name

### ISSUE THREAD

**Issue by dl1ksv** [ghostop14/gr-guiextra#3]
A usefull application of the digital number control could be setting  the frequency of a signal source.

But this fails with:

gr::log :WARN: sig_source0 - Set Frequency Message must have the key = 'freq'; got 'value'.

So I propose to change the output message key to freq or make it a configuration option.

**Comment by ghostop14** [comment]
I'll add a param to the properties to let folks control the output message name.  Probably more flexible that way.   I'll push an update tonight.

**Comment by ghostop14** [comment]
Pushed an update.  The output message name is now user-configurable and defaults to freq.
