### ISSUE TITLE
Error: No module named 'guiextra'

### ISSUE THREAD

**Issue by efakhri** [ghostop14/gr-guiextra#6]
I've built gr-guiextra using:
`cd
git clone https://github.com/ghostop14/gr-guiextra.git
cd ~/gr-guiextra
git checkout maint-3.8
mkdir build
cd build
cmake ../
make
sudo make install
sudo ldconfig`
i got this error when run gui compass gnuradio:
`Traceback (most recent call last):
  File "/home/fakhri/gnu/ok.py", line 39, in <module>
    import guiextra
ModuleNotFoundError: No module named 'guiextra'`

**Comment by duggabe** [comment]
I have the same problem
Xubuntu 21.04
GNU Radio 3.8.0.0

**Comment by ghostop14** [comment]
I've most often seen that when the python path isn't correct, or if something happened during cmake and I didn't notice.

You might also get some extra debug info from trying this:
export LD_DEBUG=libs 
python3 
import guiextra

**Comment by duggabe** [comment]
I got my paths fixed and it works OK now.

**Comment by ghostop14** [comment]
Awesome!
